spring:
  application:
    name: plain_jpa
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: password
    url: jdbc:postgresql://localhost:5432/bicycle
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect